### ISSUE TITLE
Publish build for globals users.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-legacy-views#12]

**Comment by pixelhandler** [comment]
@rwjblue this is very important for long-lived apps that need legacy views. It does seem odd to me that the legacy solution is dependent a recently stable build pipeline (ember-cli) without providing a global for apps that have existed on the previous recommended build pipeline prior to ember-cli.

**Comment by stefanpenner** [comment]
> It does seem odd to me

This is a function of available time and an indicator of why the ember-cli based approach is appealing.

 This doesn't prevent someone from producing global builds at a later point in time, just as liquidfire does via ember-giftwrap

> Seems like "here is a solution for legacy support, but now update your entire app to current so you can have legacy support"

This isn't a fair or accurate statement.

One approach, and likely the one @rwjblue intends to take is via https://github.com/ef4/ember-giftwrap. Maybe you or someone else in an itch-scratching mood can help out. At some point in the future, there will be a globals build.

**Comment by pixelhandler** [comment]
@stefanpenner The following twitter conversation to me explains how the messaging about the upgrade path from 1.x to 2.x is also 'not accurate' ... https://twitter.com/pixelhandler/status/622194552422543360

Actually, as you've described, there is work to be done and some work is left for those to pick up the change or get left behind.

Yeah, I've done the 'globals' build before and supplied that as first class citizen in an addon. https://github.com/pixelhandler/ember-off-canvas-components/blob/master/packaging/README-packaging.md following the example by liquid-fire / @ef4 

I do notice the **WIP** in the https://github.com/ef4/ember-giftwrap project. About 8 months back I tried to promote and share how it's a great idea to include a globals release of add ons http://pixelhandler.com/posts/develop-embercomponents-for-sharing-as-ember-cli-addons-a-practical-example 

What bothers me is that for a legacy solution… a globals release is not yet first class in the solution. Yeah, I get the need to embrace components.  A long term support plan is needed which I think the legacy solutions help out with. *It just appears to me more of an afterthought and not a priority.* 

> This is a function of available time

… to me that just means other things are more important.

**Every time I want to update there is yet another blocker standing in the way. bummer.**

Sorry to vent, I'll try and help as I'll need it anyway.

**Comment by rwjblue** [comment]
> … to me that just means other things are more important.

Yup, precisely. We all have many irons in the fire, prioritization is always a reality. At some point this will be important enough for someone that needs it to jump in and do the work needed. That is the beauty of open source.

> Sorry to vent, I'll try and help as I'll need it anyway.

Sounds great! Help is much more likely to have a positive result.

**Comment by pixelhandler** [comment]
@rwjblue, @stefanpenner - the more I think about it and the work ahead of me… views -> components, globals (in coffee) using asset pipeline -> ember-cli (es6), fix deprecations in various apps and core libraries, address a growing backlog of features. You guys are right, this is a low priority (contributing to global build of a legacy addon); a global build from an addon is not a new idea - it just hasn't gained much interest in the community. 

I'd only be buying some time till v2.4; I'm not convinced yet that it's worth the effort, compared with not upgrading and just rewriting. We've been on this road for a while now… fat views -> thinner views plus controllers w/ actions -> transition from views to components and action bubbling -> and now leaving views and controllers behind for components. Legacy support seems to be a new and temporary idea, legacy support does seem more second class than first class in the Ember economy. I don't have a high confidence it's the right road for me to travel down.

**Comment by stefanpenner** [comment]
I don't believe this issue is the correct venue for this discussion. For some reason, this conversation keeps coming up as a tangent on other threads. 

This issue exists to provide the requested legacy support, it is actionable and well defined, it does not exist to lament.

As mentioned before, we take bug reports related to upgrade pain very seriously. But they must be actionable, such as "this problem X, prevents me from upgrading".

**Comment by pixelhandler** [comment]
This issue of not having a global release for legacy views blocks my team from upgrading to 2.x.

What is the direction for the solution https://github.com/ef4/ember-giftwrap or a one-off stand-alone build step like so https://github.com/pixelhandler/ember-off-canvas-components/tree/master/packaging ??

**Comment by perlun** [comment]
Publishing a "build" of this package is really overkill. The only thing you need to do to get legacy views enabled is the following:

``` javascript
<script>
    window.EmberENV = {
      "_ENABLE_LEGACY_VIEW_SUPPORT": true
    };
</script>
```

Make sure to run that _before_ you load the `ember.js` file. That's really all it takes; Ember.View and friends will now be available (but of course, try to migrate away from using this class if at all possible...).
