### ISSUE TITLE
Installing ember-legacy-views if you don't have ember-cli

### ISSUE THREAD

**Issue by tyreepace** [emberjs/ember-legacy-views#13]
Hi - our ember app does not use ember-cli. Is there a way to install or include ember-legacy-views if we are not on ember-cli? We are moving our app to ember 1.13 but aren't ready to be rid of Ember.View just yet. Thanks!

**Comment by rwjblue** [comment]
You can use ember-giftwrap to create a globals build for any combination of addons.

**Comment by pixelhandler** [comment]
@rwjblue so does ember-legacy-views already use ember-giftwrap to provide a solution for apps not yet on ember-cli?

(ember-cli did just become stable so long-lived apps that need legacy views most likely are not using ember-cli yet).

oh wait I see #12

**Comment by stefanpenner** [comment]
superseded by #12
