### ISSUE TITLE
update README to mention using latest ember-cli-htmlbars to silence build warnings

### ISSUE THREAD

**Issue by bantic** [emberjs/ember-legacy-views#8]
ember-cli-htmlbars@0.7.9 has an update that makes it possible for this addon to affect the ember environment early enough to silence the compilation warnings that would otherwise appear in `ember serve`'s output. Update the readme to mention this.

See https://github.com/emberjs/ember.js/pull/11418#issuecomment-111606806

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/4288 updates ember-cli's default
